TOPICS = [
    "agents",
    "evals",
    "retrieval",
    "reasoning",
    "multimodal",
    "alignment",
    "inference",
    "embeddings",
    "distillation",
    "tooling",
    "orchestration",
    "memory",
    "vectorsearch",
    "finetuning",
    "simulation",
]
